#![cfg_attr(not(test), warn(clippy::too_many_lines, unreachable_pub))]

use starmux::{Application, Focus, ProcessTmux, Sidebar};
use std::{collections::BTreeMap, path::PathBuf};
use unicode_segmentation::UnicodeSegmentation;
use unicode_width::UnicodeWidthStr;

fn config_path() -> Option<PathBuf> {
    if let Some(value) = std::env::var_os("STARMUX_CONFIG") {
        return Some(PathBuf::from(value));
    }
    let root = std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|home| PathBuf::from(home).join(".config")))?;
    Some(root.join("starmux.toml"))
}

fn load_sidebar() -> Result<Sidebar, String> {
    let Some(path) = config_path() else {
        return Sidebar::defaults();
    };
    let text = match std::fs::read_to_string(&path) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(error) => return Err(format!("{}: {error}", path.display())),
    };
    Sidebar::from_toml(&text).map_err(|error| format!("{}: {error}", path.display()))
}

fn adapter() -> &'static str {
    "# Generated by starmux init tmux. Sidebar position, width, and style remain tmux options.\nset -g side-status-format '#(starmux render-query --width=#{e|-:#{side-status-width},1} --socket=#{q/s:socket_path} --client=#{q/s:client_name} --current-session=#{q/s:session_id} --current-window=#{q/s:window_id})'\nbind -n MouseDown1Status { if -F '#{m/r:^(st|sw|sp|su|sr|sl|ss|sc),#{mouse_status_range}}' { run-shell -b 'starmux activate --width=#{e|-:#{side-status-width},1} --socket=#{q/s:socket_path} --client=#{q/s:client_name} --target=#{q/s:mouse_status_range}' } { if -F '#{!=:#{mouse_status_range},sv}' { switch-client -t= } } }\nbind -n WheelUpStatus { if -F '#{m/r:^(st|sw|sp|su|sr|sl|ss|sc|sv),#{mouse_status_range}}' { run-shell 'starmux scroll-event --width=#{e|-:#{side-status-width},1} --socket=#{q/s:socket_path} --client=#{q/s:client_name} --direction=up' } { previous-window } }\nbind -n WheelDownStatus { if -F '#{m/r:^(st|sw|sp|su|sr|sl|ss|sc|sv),#{mouse_status_range}}' { run-shell 'starmux scroll-event --width=#{e|-:#{side-status-width},1} --socket=#{q/s:socket_path} --client=#{q/s:client_name} --direction=down' } { next-window } }\n"
}

fn flags(values: &[String]) -> Result<BTreeMap<&str, &str>, String> {
    let mut result = BTreeMap::new();
    for value in values {
        let Some((name, value)) = value
            .strip_prefix("--")
            .and_then(|value| value.split_once('='))
        else {
            return Err(format!("invalid argument {value}"));
        };
        if result.insert(name, value).is_some() {
            return Err(format!("duplicate --{name}"));
        }
    }
    Ok(result)
}

fn query_arguments(values: &[String]) -> Result<(usize, &str, &str, Option<Focus>, &str), String> {
    let flags = flags(values)?;
    let width = flags
        .get("width")
        .ok_or("missing --width")?
        .parse::<usize>()
        .map_err(|_| "invalid --width")?;
    let socket = *flags.get("socket").ok_or("missing --socket")?;
    let client = *flags.get("client").ok_or("missing --client")?;
    let focus = match (flags.get("current-session"), flags.get("current-window")) {
        (None, None) => None,
        (Some(session), Some(window)) => Some(Focus::new(*session, *window)?),
        _ => return Err("expected both --current-session and --current-window".into()),
    };
    let config = flags.get("config").copied().unwrap_or("default");
    let expected = if focus.is_some() { 5 } else { 3 };
    if flags.len() != expected + usize::from(flags.contains_key("config")) {
        return Err("unknown render-query argument".into());
    }
    Ok((width, socket, client, focus, config))
}

fn usage_refresh(args: &[String]) -> Result<(), String> {
    let parsed = flags(args)?;
    if parsed.len() != 2 {
        return Err("usage: starmux usage-refresh --provider=NAME --data-dir=PATH".into());
    }
    let provider = parsed.get("provider").ok_or("missing --provider")?;
    let dir = parsed.get("data-dir").ok_or("missing --data-dir")?;
    let mut token = String::new();
    use std::io::Read;
    std::io::stdin()
        .take(128)
        .read_to_string(&mut token)
        .map_err(|error| error.to_string())?;
    starmux::usage::refresh(provider, std::path::Path::new(dir), &token)
}

fn interaction_width(parsed: &BTreeMap<&str, &str>) -> Result<Option<usize>, String> {
    parsed
        .get("width")
        .map(|width| width.parse().map_err(|_| "invalid --width".into()))
        .transpose()
}

fn scroll_command(args: &[String], refresh: bool) -> Result<(), String> {
    let parsed = flags(args)?;
    if parsed.len()
        != 3 + usize::from(parsed.contains_key("config"))
            + usize::from(parsed.contains_key("width"))
    {
        return Err(
            "usage: starmux scroll --socket=PATH --client=NAME --direction=up|down [--config=NAME] [--width=COLUMNS]"
                .into(),
        );
    }
    let config = parsed.get("config").copied().unwrap_or("default");
    let app = Application::new(load_sidebar()?.select(config)?, ProcessTmux);
    let direction = match *parsed.get("direction").ok_or("missing --direction")? {
        "up" => starmux::ScrollDirection::Up,
        "down" => starmux::ScrollDirection::Down,
        _ => return Err("invalid --direction".into()),
    };
    let _ = app.scroll(
        parsed.get("socket").ok_or("missing --socket")?,
        parsed.get("client").ok_or("missing --client")?,
        direction,
        interaction_width(&parsed)?,
        refresh,
    )?;
    Ok(())
}

fn activate_command(args: &[String]) -> Result<(), String> {
    let parsed = flags(args)?;
    if parsed.len()
        != 3 + usize::from(parsed.contains_key("config"))
            + usize::from(parsed.contains_key("width"))
    {
        return Err(
            "usage: starmux activate --socket=PATH --client=NAME --target=TOKEN [--config=NAME] [--width=COLUMNS]"
                .into(),
        );
    }
    let app = Application::new(
        load_sidebar()?.select(parsed.get("config").copied().unwrap_or("default"))?,
        ProcessTmux,
    );
    app.activate_at_width(
        parsed.get("socket").ok_or("missing --socket")?,
        parsed.get("client").ok_or("missing --client")?,
        parsed.get("target").ok_or("missing --target")?,
        interaction_width(&parsed)?,
    )
}

fn top_refresh(args: &[String]) -> Result<(), String> {
    match args {
        [_, dir, token] => starmux::top::refresh(std::path::Path::new(dir), token),
        _ => Err("invalid top worker arguments".into()),
    }
}

fn run() -> Result<(), String> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let command = args
        .first()
        .map(String::as_str)
        .ok_or("expected a command")?;
    if args.len() == 1 && matches!(command, "--version" | "-V") {
        println!("starmux {}", env!("CARGO_PKG_VERSION"));
        return Ok(());
    }
    if args.len() == 1 && matches!(command, "--help" | "-h") {
        println!(
            "starmux {}\n\nUsage:\n  starmux init tmux\n  starmux render-query --width=COLUMNS --socket=PATH --client=NAME [--current-session=ID --current-window=ID] [--config=NAME]\n  starmux explain --width=COLUMNS --socket=PATH --client=NAME [--current-session=ID --current-window=ID] [--config=NAME]\n  starmux timings --width=COLUMNS --socket=PATH --client=NAME [--current-session=ID --current-window=ID] [--config=NAME]\n  starmux activate --socket=PATH --client=NAME --target=TOKEN [--config=NAME] [--width=COLUMNS]\n  starmux scroll --socket=PATH --client=NAME --direction=up|down [--config=NAME] [--width=COLUMNS]\n  starmux check-config\n  starmux print-config",
            env!("CARGO_PKG_VERSION")
        );
        return Ok(());
    }
    if command == "init" {
        return match args.as_slice() {
            [_, target] if target == "tmux" => {
                print!("{}", adapter());
                Ok(())
            }
            _ => Err("usage: starmux init tmux".into()),
        };
    }
    if command == "pr-refresh" {
        return match args.as_slice() {
            [_, url, dir] => starmux::pr_state::refresh(url, std::path::Path::new(dir)),
            _ => Err("usage: starmux pr-refresh URL CACHE_DIR".into()),
        };
    }
    if command == "usage-refresh" {
        return usage_refresh(&args[1..]);
    }
    if command == "top-refresh" {
        return top_refresh(&args);
    }
    if command == "scroll-worker" {
        return match args.as_slice() {
            [_, socket_flag, socket, client_flag, client]
                if socket_flag == "--socket" && client_flag == "--client" =>
            {
                starmux::scroll_worker(socket, client)
            }
            [_, socket_flag, socket, client_flag, client, config_flag, config]
                if socket_flag == "--socket"
                    && client_flag == "--client"
                    && config_flag == "--config" =>
            {
                starmux::scroll_worker_for(socket, client, config)
            }
            [_, socket_flag, socket, client_flag, client, config_flag, config, dir_flag, dir]
                if socket_flag == "--socket"
                    && client_flag == "--client"
                    && config_flag == "--config"
                    && dir_flag == "--dir" =>
            {
                starmux::scroll_worker_in(socket, client, config, std::path::Path::new(dir))
            }
            _ => Err("invalid scroll worker arguments".into()),
        };
    }
    if matches!(command, "scroll" | "scroll-event") {
        return scroll_command(&args[1..], command == "scroll");
    }
    if command == "activate" {
        return activate_command(&args[1..]);
    }

    let sidebar = load_sidebar()?;
    if command == "check-config" {
        if args.len() != 1 {
            return Err("usage: starmux check-config".into());
        }
        println!("configuration valid");
        return Ok(());
    }
    if command == "print-config" {
        if args.len() != 1 {
            return Err("usage: starmux print-config".into());
        }
        print!("{}", sidebar.print_config()?);
        return Ok(());
    }
    if !matches!(command, "render-query" | "explain" | "timings") {
        return Err(format!("unknown command {command}"));
    }
    let (width, socket, client, focus, config) = query_arguments(&args[1..])?;
    let app = Application::new(sidebar.select(config)?, ProcessTmux);
    match command {
        "render-query" => println!(
            "{}",
            app.render_query(socket, client, width, focus.as_ref())?
        ),
        "explain" => print!("{}", app.explain(socket, client, width, focus.as_ref())?),
        "timings" => println!("{}", app.timings(socket, client, width, focus.as_ref())?),
        _ => unreachable!(),
    }
    Ok(())
}

fn error_width(args: &[String]) -> usize {
    args.iter()
        .filter_map(|arg| arg.strip_prefix("--width="))
        .find_map(|value| {
            value
                .parse::<usize>()
                .ok()
                .filter(|width| (2..=300).contains(width))
        })
        .unwrap_or(30)
}

fn render_error(error: &str, width: usize) -> String {
    let mut result = String::from("#[fg=red]");
    let mut column = 0;
    for (index, line) in error.split('\n').enumerate() {
        if index > 0 {
            result.push_str("#[nl]#[fg=red]");
            column = 0;
        }
        for grapheme in line.graphemes(true) {
            let text = if grapheme.chars().any(char::is_control) {
                " "
            } else {
                grapheme
            };
            let size = UnicodeWidthStr::width(text);
            if column > 0 && column + size > width {
                result.push_str("#[nl]#[fg=red]");
                column = 0;
            }
            result.push_str(&text.replace('#', "##"));
            column += size;
        }
    }
    result.push_str("#[default]");
    result
}

fn main() {
    if let Err(error) = run() {
        let diagnostic = format!("starmux: {error}");
        eprintln!("{diagnostic}");
        let args: Vec<String> = std::env::args().skip(1).collect();
        if args
            .first()
            .is_some_and(|command| command == "render-query")
        {
            println!("{}", render_error(&diagnostic, error_width(&args[1..])));
        }
        std::process::exit(2);
    }
}
