mod config;
mod input;
mod navigation;
mod provider;
mod query;
mod view;

use std::{
    io::{self, Write},
    time::Instant,
};
use view::Row;

fn transport() -> String {
    let session = "--session-id=#{q/s:session_id} --session-name=#{q/s:session_name} --window-count=#{session_windows}";
    let window = "--window-id=#{window_id} --window-index=#{window_index} --window-name=#{q/s:window_name} --selected=#{window_active} --window-pane=#{pane_id} --window-path=#{q/s:pane_current_path} --pi-state=#{q/s:@pi_win_state} --window-icon=#{q/s:@window_icon} --end-window";
    format!("--input-version=1 --width=30 --client-width=#{{client_width}} --client-height=#{{client_height}} --current-session=#{{q/s:session_id}} --current-pane=#{{pane_id}} --pane-path=#{{q/s:pane_current_path}} --session-count=#{{server_sessions}} #{{S:{session} #{{W:{window} }} --end-session }}")
}

fn mouse_binding() -> &'static str {
    "bind -n MouseDown1Status { if -F '#{m/r:^sw,#{mouse_status_range}}' { run-shell -b 'starmux activate --socket=#{q/s:socket_path} --client=#{q/s:client_name} --target=#{q/s:mouse_status_range}' } { switch-client -t= } }\n"
}

fn adapter() -> String {
    format!("# Generated by starmux init tmux; protocol version 1.\n# Pass the socket, client, and expected focus; the CLI verifies its tmux query.\n# Focus changes also make tmux run a new format job.\nset -g side-status left\nset -g side-status-width 30\nset -g side-status-style 'fg=#828bb8,bg=#1b1d2b'\nset -g side-status-format '#(starmux render-query --socket=#{{q/s:socket_path}} --client=#{{q/s:client_name}} --current-session=#{{q/s:session_id}} --current-window=#{{q/s:window_id}})'\n{}", mouse_binding())
}

fn argv_adapter() -> String {
    format!("# Generated by starmux init tmux-argv; protocol version 1.\n# The legacy adapter passes a shell-quoted snapshot instead of querying tmux.\nset -g side-status left\nset -g side-status-width 30\nset -g side-status-style 'fg=#828bb8,bg=#1b1d2b'\nset -g side-status-format '#(starmux render {})'\n{}", transport(), mouse_binding())
}

fn modules(
    ctx: &input::Context,
    cfg: &config::Config,
    select: Option<&str>,
    facts: &std::collections::BTreeMap<String, provider::Facts>,
) -> Result<Vec<Row>, String> {
    let names = if let Some(name) = select {
        config::modules(&format!("${name}"))?
    } else {
        config::modules(&cfg.format)?
    };
    let mut rows = Vec::new();
    for name in names {
        match name.as_str() {
            "sessions" => rows.extend(view::sessions(ctx)?),
            "divider" => rows.extend(view::divider(ctx.width)),
            _ => {
                let provider_name = &cfg
                    .module
                    .get(&name)
                    .ok_or_else(|| format!("unknown module {name}"))?
                    .provider;
                if let Some(fact) = facts.get(provider_name) {
                    rows.extend(provider::rows(fact));
                }
            }
        }
    }
    Ok(rows)
}

fn safe_error(error: &str) -> ! {
    eprintln!("starmux: {error}");
    println!("#[fg=#ffc777] starmux: input error#[default]");
    std::process::exit(2)
}

fn run() -> Result<(), String> {
    let started = Instant::now();
    let mut args: Vec<String> = std::env::args().skip(1).collect();
    let mut expected_focus = None;
    if args.first().is_some_and(|arg| arg == "render-query") {
        let socket = args
            .get(1)
            .and_then(|arg| arg.strip_prefix("--socket="))
            .ok_or(query::USAGE)?;
        let client = args
            .get(2)
            .and_then(|arg| arg.strip_prefix("--client="))
            .ok_or(query::USAGE)?;
        expected_focus = query::Focus::parse(&args[3..])?;
        let mut snapshot = vec!["render".into()];
        snapshot.extend(query::snapshot(socket, client)?);
        args = snapshot;
    }
    if std::env::var_os("STARMUX_DEBUG_ARGS").is_some() {
        eprintln!("starmux argv: {args:?}");
    }
    let command = args
        .first()
        .map(String::as_str)
        .ok_or("expected a command")?;
    if args.len() == 1 && matches!(command, "--version" | "-V") {
        println!("starmux {}", env!("CARGO_PKG_VERSION"));
        return Ok(());
    }
    if args.len() == 1 && matches!(command, "--help" | "-h") {
        println!("starmux {}\n\nUsage:\n  starmux init tmux\n  starmux render-query --socket=PATH --client=NAME [--current-session=ID --current-window=ID]\n  starmux activate --socket=PATH --client=NAME --target=TOKEN\n  starmux check-config\n  starmux print-config\n\nSee README.md for providers and the versioned snapshot commands.", env!("CARGO_PKG_VERSION"));
        return Ok(());
    }
    if command == "init" {
        match args.as_slice() {
            [_, target] if target == "tmux" => print!("{}", adapter()),
            [_, target] if target == "tmux-argv" => print!("{}", argv_adapter()),
            _ => return Err("usage: starmux init tmux|tmux-argv".into()),
        }
        return Ok(());
    }
    if command == "activate" {
        let [_, socket, client, target] = args.as_slice() else {
            return Err(
                "usage: starmux activate --socket=PATH --client=NAME --target=TOKEN".into(),
            );
        };
        let socket = socket.strip_prefix("--socket=").ok_or("invalid --socket")?;
        let client = client.strip_prefix("--client=").ok_or("invalid --client")?;
        let target = target.strip_prefix("--target=").ok_or("invalid --target")?;
        return navigation::activate(socket, client, target);
    }
    let cfg = config::load()?;
    if command == "print-config" {
        print!(
            "{}",
            toml::to_string_pretty(&cfg).map_err(|e| e.to_string())?
        );
        return Ok(());
    }
    if command == "check-config" {
        println!("configuration valid");
        return Ok(());
    }
    let selected = if matches!(command, "module" | "provider") {
        Some(args.get(1).ok_or("missing module/provider name")?.as_str())
    } else {
        None
    };
    if !matches!(
        command,
        "render" | "refresh" | "module" | "provider" | "explain" | "timings"
    ) {
        return Err(format!("unknown command {command}"));
    }
    let context = input::parse(&args[if selected.is_some() { 2 } else { 1 }..])?;
    if let Some(focus) = expected_focus {
        focus.verify(&context)?;
    }
    let parsed = started.elapsed();
    let names = if let Some(name) = selected.filter(|_| command == "module") {
        config::modules(&format!("${name}"))?
    } else {
        config::modules(&cfg.format)?
    };
    let mut wanted: Vec<String> = if command == "provider" {
        vec![selected.unwrap().to_string()]
    } else {
        names
            .iter()
            .filter_map(|name| cfg.module.get(name).map(|m| m.provider.clone()))
            .collect()
    };
    wanted.sort();
    wanted.dedup();
    let (cached, stale) = provider::cached(&cfg, &context, &wanted);
    if command == "refresh" {
        let refreshed = provider::run(&cfg, &context, &stale);
        provider::hide_failed(&cfg, &context, &stale, &refreshed);
        return Ok(());
    }
    if command == "provider" {
        let results = provider::run(&cfg, &context, &stale);
        println!(
            "{}",
            serde_json::to_string(&results).map_err(|e| e.to_string())?
        );
        return Ok(());
    }
    let rendered = modules(&context, &cfg, selected, &cached)?;
    if command == "explain" {
        println!(
            "modules: {}\nproviders: {}\ncache hits: {}\nclient: {}x{} pane {}",
            names.join(", "),
            wanted.join(", "),
            cached.len(),
            context.client_width,
            context.client_height,
            context.current_pane
        );
        for session in &context.sessions {
            println!("session {} {:?}", session.id, session.name);
            for window in &session.windows {
                println!(
                    "  window {} index={} pane={} path={:?} selected={}",
                    window.id, window.index, window.pane, window.path, window.selected
                );
            }
        }
        return Ok(());
    }
    let first = view::render(&rendered, context.width);
    let first_time = started.elapsed();
    if command == "timings" {
        let refreshed = provider::run(&cfg, &context, &stale);
        println!(
            "{}",
            serde_json::json!({"parse_us": parsed.as_micros(), "first_us": first_time.as_micros(), "settled_us": started.elapsed().as_micros(), "providers": refreshed.len()})
        );
        return Ok(());
    }
    let stdout = io::stdout();
    let mut out = stdout.lock();
    writeln!(out, "{first}").map_err(|e| e.to_string())?;
    out.flush().map_err(|e| e.to_string())?;
    if command == "render" && std::env::var_os("STARMUX_PROGRESSIVE").is_none() {
        if !stale.is_empty() {
            let mut refresh =
                std::process::Command::new(std::env::current_exe().map_err(|e| e.to_string())?);
            refresh
                .arg("refresh")
                .args(&args[1..])
                .stdin(std::process::Stdio::null())
                .stdout(std::process::Stdio::null())
                .stderr(std::process::Stdio::null());
            #[cfg(unix)]
            {
                use std::os::unix::process::CommandExt;
                unsafe {
                    refresh.pre_exec(|| {
                        if libc::setsid() >= 0 {
                            Ok(())
                        } else {
                            Err(io::Error::last_os_error())
                        }
                    });
                }
            }
            refresh.spawn().map_err(|e| e.to_string())?;
        }
        return Ok(());
    }
    let refreshed = provider::run(&cfg, &context, &stale);
    let mut updated = cached;
    for name in &stale {
        if !refreshed.contains_key(name)
            && cfg.provider.get(name).is_some_and(|p| p.failure == "hide")
        {
            updated.remove(name);
        }
    }
    updated.extend(refreshed);
    let next = view::render(&modules(&context, &cfg, selected, &updated)?, context.width);
    if next != first {
        writeln!(out, "{next}").map_err(|e| e.to_string())?;
        out.flush().map_err(|e| e.to_string())?;
    }
    Ok(())
}

fn main() {
    if let Err(error) = run() {
        safe_error(&error);
    }
}
