#![cfg_attr(not(test), warn(clippy::too_many_lines, unreachable_pub))]

use clap::{Args, Parser, Subcommand, ValueEnum};
use starmux::{Application, Focus, ProcessTmux, ScrollDirection, Sidebar};
use std::path::{Path, PathBuf};
use unicode_segmentation::UnicodeSegmentation;
use unicode_width::UnicodeWidthStr;

fn config_path() -> Option<PathBuf> {
    if let Some(value) = std::env::var_os("STARMUX_CONFIG") {
        return Some(PathBuf::from(value));
    }
    let root = std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|home| PathBuf::from(home).join(".config")))?;
    Some(root.join("starmux.toml"))
}

fn load_sidebar() -> Result<Sidebar, String> {
    let Some(path) = config_path() else {
        return Sidebar::defaults();
    };
    let text = match std::fs::read_to_string(&path) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(error) => return Err(format!("{}: {error}", path.display())),
    };
    Sidebar::from_toml(&text).map_err(|error| format!("{}: {error}", path.display()))
}

fn adapter() -> &'static str {
    "# Generated by starmux init tmux. Sidebar position, width, and style remain tmux options.\nset -g side-status-format '#(starmux render-query --width=#{e|-:#{side-status-width},1} --socket=#{q/s:socket_path} --client=#{q/s:client_name} --current-session=#{q/s:session_id} --current-window=#{q/s:window_id})'\nbind -n MouseDown1Status { if -F '#{m/r:^(st|sw|sp|su|sr|sl|ss|sc),#{mouse_status_range}}' { run-shell -b 'starmux activate --width=#{e|-:#{side-status-width},1} --socket=#{q/s:socket_path} --client=#{q/s:client_name} --target=#{q/s:mouse_status_range}' } { if -F '#{!=:#{mouse_status_range},sv}' { switch-client -t= } } }\nbind -n WheelUpStatus { if -F '#{m/r:^(st|sw|sp|su|sr|sl|ss|sc|sv),#{mouse_status_range}}' { run-shell 'starmux scroll-event --width=#{e|-:#{side-status-width},1} --socket=#{q/s:socket_path} --client=#{q/s:client_name} --direction=up' } { previous-window } }\nbind -n WheelDownStatus { if -F '#{m/r:^(st|sw|sp|su|sr|sl|ss|sc|sv),#{mouse_status_range}}' { run-shell 'starmux scroll-event --width=#{e|-:#{side-status-width},1} --socket=#{q/s:socket_path} --client=#{q/s:client_name} --direction=down' } { next-window } }\n"
}

#[derive(Parser)]
#[command(
    name = "starmux",
    version,
    about = "A fast and configurable tmux sidebar",
    arg_required_else_help = true
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    #[command(about = "Print the tmux configuration that renders the sidebar")]
    Init { target: InitTarget },
    #[command(about = "Render the sidebar for tmux side-status")]
    RenderQuery(QueryArgs),
    #[command(about = "Explain how each sidebar row was rendered")]
    Explain(QueryArgs),
    #[command(about = "Report sidebar render timings")]
    Timings(QueryArgs),
    #[command(about = "Run the action of a clicked sidebar row")]
    Activate {
        #[command(flatten)]
        client: ClientArgs,
        #[arg(long, value_name = "TOKEN")]
        target: String,
    },
    #[command(about = "Scroll the sidebar and refresh tmux")]
    Scroll(ScrollArgs),
    #[command(about = "Scroll the sidebar from a tmux wheel binding")]
    ScrollEvent(ScrollArgs),
    #[command(about = "Validate the configuration")]
    CheckConfig,
    #[command(about = "Print the complete configuration")]
    PrintConfig,
    #[command(hide = true)]
    PrRefresh { url: String, dir: PathBuf },
    #[command(hide = true)]
    UsageRefresh {
        #[arg(long)]
        provider: String,
        #[arg(long)]
        data_dir: PathBuf,
    },
    #[command(hide = true)]
    TopRefresh { dir: PathBuf, token: String },
    #[command(hide = true)]
    ScrollWorker {
        #[arg(long)]
        socket: String,
        #[arg(long)]
        client: String,
        #[arg(long, default_value = "default")]
        config: String,
        #[arg(long)]
        dir: Option<PathBuf>,
    },
}

#[derive(Args)]
struct QueryArgs {
    #[arg(long, value_name = "COLUMNS")]
    width: usize,
    #[arg(long, value_name = "PATH")]
    socket: String,
    #[arg(long, value_name = "NAME")]
    client: String,
    #[arg(long, value_name = "ID", requires = "current_window")]
    current_session: Option<String>,
    #[arg(long, value_name = "ID", requires = "current_session")]
    current_window: Option<String>,
    #[arg(long, value_name = "NAME", default_value = "default")]
    config: String,
}

#[derive(Args)]
struct ClientArgs {
    #[arg(long, value_name = "PATH")]
    socket: String,
    #[arg(long, value_name = "NAME")]
    client: String,
    #[arg(long, value_name = "NAME", default_value = "default")]
    config: String,
    #[arg(long, value_name = "COLUMNS")]
    width: Option<usize>,
}

#[derive(Args)]
struct ScrollArgs {
    #[command(flatten)]
    client: ClientArgs,
    #[arg(long, value_enum)]
    direction: Direction,
}

#[derive(Clone, ValueEnum)]
enum InitTarget {
    Tmux,
}

#[derive(Clone, ValueEnum)]
enum Direction {
    Up,
    Down,
}

impl From<Direction> for ScrollDirection {
    fn from(direction: Direction) -> Self {
        match direction {
            Direction::Up => Self::Up,
            Direction::Down => Self::Down,
        }
    }
}

fn application(config: &str) -> Result<Application<ProcessTmux>, String> {
    Ok(Application::new(
        load_sidebar()?.select(config)?,
        ProcessTmux,
    ))
}

fn usage_refresh(provider: &str, dir: &Path) -> Result<(), String> {
    use std::io::Read;
    let mut token = String::new();
    std::io::stdin()
        .take(128)
        .read_to_string(&mut token)
        .map_err(|error| error.to_string())?;
    starmux::usage::refresh(provider, dir, &token)
}

fn scroll(args: &ScrollArgs, refresh: bool) -> Result<(), String> {
    let client = &args.client;
    application(&client.config)?.scroll(
        &client.socket,
        &client.client,
        args.direction.clone().into(),
        client.width,
        refresh,
    )?;
    Ok(())
}

fn query(command: &Command, args: &QueryArgs) -> Result<(), String> {
    let focus = match (&args.current_session, &args.current_window) {
        (Some(session), Some(window)) => Some(Focus::new(session.as_str(), window.as_str())?),
        _ => None,
    };
    let app = application(&args.config)?;
    let (socket, client, width, focus) = (&args.socket, &args.client, args.width, focus.as_ref());
    match command {
        Command::RenderQuery(_) => println!("{}", app.render_query(socket, client, width, focus)?),
        Command::Explain(_) => print!("{}", app.explain(socket, client, width, focus)?),
        _ => println!("{}", app.timings(socket, client, width, focus)?),
    }
    Ok(())
}

fn run(command: &Command) -> Result<(), String> {
    match command {
        Command::Init {
            target: InitTarget::Tmux,
        } => print!("{}", adapter()),
        Command::RenderQuery(args) | Command::Explain(args) | Command::Timings(args) => {
            query(command, args)?;
        }
        Command::Activate { client, target } => application(&client.config)?.activate_at_width(
            &client.socket,
            &client.client,
            target,
            client.width,
        )?,
        Command::Scroll(args) => scroll(args, true)?,
        Command::ScrollEvent(args) => scroll(args, false)?,
        Command::CheckConfig => {
            load_sidebar()?;
            println!("configuration valid");
        }
        Command::PrintConfig => print!("{}", load_sidebar()?.print_config()?),
        Command::PrRefresh { url, dir } => starmux::pr_state::refresh(url, dir)?,
        Command::UsageRefresh { provider, data_dir } => usage_refresh(provider, data_dir)?,
        Command::TopRefresh { dir, token } => starmux::top::refresh(dir, token)?,
        Command::ScrollWorker {
            socket,
            client,
            config,
            dir: Some(dir),
        } => starmux::scroll_worker_in(socket, client, config, dir)?,
        Command::ScrollWorker {
            socket,
            client,
            config,
            dir: None,
        } => starmux::scroll_worker_for(socket, client, config)?,
    }
    Ok(())
}

fn error_width(args: &[String]) -> usize {
    args.iter()
        .filter_map(|arg| arg.strip_prefix("--width="))
        .find_map(|value| {
            value
                .parse::<usize>()
                .ok()
                .filter(|width| (2..=300).contains(width))
        })
        .unwrap_or(30)
}

fn render_error(error: &str, width: usize) -> String {
    let mut result = String::from("#[fg=red]");
    let mut column = 0;
    for (index, line) in error.split('\n').enumerate() {
        if index > 0 {
            result.push_str("#[nl]#[fg=red]");
            column = 0;
        }
        for grapheme in line.graphemes(true) {
            let text = if grapheme.chars().any(char::is_control) {
                " "
            } else {
                grapheme
            };
            let size = UnicodeWidthStr::width(text);
            if column > 0 && column + size > width {
                result.push_str("#[nl]#[fg=red]");
                column = 0;
            }
            result.push_str(&text.replace('#', "##"));
            column += size;
        }
    }
    result.push_str("#[default]");
    result
}

fn fail(error: &str, render_query: bool) -> ! {
    let diagnostic = format!("starmux: {error}");
    if render_query {
        let args: Vec<String> = std::env::args().skip(2).collect();
        println!("{}", render_error(&diagnostic, error_width(&args)));
    }
    std::process::exit(2);
}

fn main() {
    let cli = match Cli::try_parse() {
        Ok(cli) => cli,
        Err(error) if !error.use_stderr() => error.exit(),
        Err(error) => {
            let _ = error.print();
            let text = error.render().to_string();
            let summary = text
                .lines()
                .take_while(|line| !line.trim().is_empty())
                .map(str::trim)
                .collect::<Vec<_>>()
                .join(" ");
            let render_query = std::env::args().nth(1).as_deref() == Some("render-query");
            fail(
                summary.strip_prefix("error: ").unwrap_or(&summary),
                render_query,
            );
        }
    };
    if let Err(error) = run(&cli.command) {
        eprintln!("starmux: {error}");
        fail(&error, matches!(cli.command, Command::RenderQuery(_)));
    }
}
